language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t ezaragozasolutel/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true ezaragozasolutel/docker-react npm run test